version: 2
project_name: pocketchip-apt-rescue

before:
  hooks:
    - go mod tidy

builds:
  - id: app
    binary: pocketchip-apt-rescue
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

dockers:
  - image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:{{ .Tag }}-amd64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:latest-amd64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:{{ .Tag }}-arm64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:latest-arm64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:{{ .Tag }}-arm
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:latest-arm
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm
    build_flag_templates:
      - "--platform=linux/arm/v7"

nfpms:
  - id: default
    package_name: pocketchip-apt-rescue
    maintainer: "arran4"
    description: "pocketchip-apt-rescue proxy for PocketCHIP"
    homepage: "https://github.com/arran4/pocketchip-apt-rescue"
    license: "MIT"
    formats:
      - deb

docker_manifests:
  - name_template: ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:{{ .Tag }}
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:{{ .Tag }}-amd64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:{{ .Tag }}-arm64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:{{ .Tag }}-arm
  - name_template: ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:latest
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:latest-amd64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:latest-arm64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY | tolower }}:latest-arm

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
